worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    upstream backend {
        server backend-rtmp:4200;
    }

    upstream frontend {
        server front-rtmp:3000;
    }

    upstream mediamtx {
        server mediamtx:8888;
    }

    server {
        listen 80;

        location /backend/ {
            proxy_pass http://backend;
            rewrite ^/backend(/.*)$ $1 break;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location / {
            proxy_pass http://frontend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /hls/ {
            proxy_pass http://mediamtx;
            rewrite ^/hls(/.*)$ $1 break;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept';
        }
    }
}
